Documentation/canvas
InteliJR/Imobiliaria pull request #13
Opened 2024-06-27 19:07 UTC by BretasArthur1

2024-06-28 15:39 UTC, omatheu requested changes
Mudar a direção do merge. Está em direção a **main**, quando o correto é em direção a **docs**.

2024-06-28 18:07 UTC, Rodrigo-07 approved these changes
Concordo com o canvas

2024-06-28 18:27 UTC, Rodrigo-07 requested changes
Concordo com tudo oq foi posto o canvas, boa 🚀

2024-06-28 18:27 UTC, Rodrigo-07 commented on docs/docs/Entendimento do problema/value_proposition_canvas.md
É bom colocar um texto introduzindo oq é o Value Proposition Canvas pra ficar mais claro oq é e o pq de estarmos fazendo ele.

2024-06-28 20:11 UTC, omatheu requested changes
Excelente trabalho @BretasArthur1 !

Acredito que só falta um textinho falando sobre o que o value proposition canvas e o porque ele é importante.

2024-06-28 20:11 UTC, omatheu commented on docs/docs/Entendimento do problema/value_proposition_canvas.md
Concordo com o @Rodrigo-07

2024-06-28 20:11 UTC, omatheu commented on docs/static/img/canvass.png
A questão de 'exibição de imóveis' a nossa solução não vai resolver, apesar de ser uma dor.

2024-06-28 22:23 UTC, BretasArthur1 commented on docs/docs/Entendimento do problema/value_proposition_canvas.md
perfeito, vou adicionar a introducao

2024-06-30 23:43 UTC, omatheu approved these changes

2024-07-01 01:54 UTC, Rodrigo-07 approved these changes
Boaa

2024-07-01 22:09 UTC, lucas-nunes-matheus reviewed
Ótimo trabalho, @BretasArthur1! 
Acredito que só precisa revisar uns detalhes:

Em "Valor Proposto", acredito que não haverá "aumento da visibilidade dos imóveis", uma vez que a plataforma não deverá exibir imóveis para potenciais clientes, somente locadores e locatários atuais.
Em "Clientes Segmentados", em "Dores", acredito que a app não irá destacar imóveis, pelo mesmo motivo indicado anteriormente.
Em "Clientes Segmentados", em "Ganhos do Cliente", só corrigir "comunicação assertiva".

2024-07-01 22:33 UTC, merged