Documentação da Matriz É/Não É - Faz/Não faz
InteliJR/Imobiliaria pull request #14
Opened 2024-06-28 03:30 UTC by Rodrigo-07

Tentei considerar também os pontos que foram discutidos na última reunião.

2024-06-28 15:47 UTC, omatheu commented
Fiquei com dúvida apenas no termo 'encargos'. Mas acredito que esta certo.

2024-06-28 15:52 UTC, omatheu requested changes

2024-06-28 15:52 UTC, omatheu commented on docs/docs/Entendimento do problema/matriz_e_naoe.md
> +Essa matriz conssite em uma ferramenta de análise de soluções que ajuda a identificar o que de fato estamos desenvolvendo e o que isso tem de funcionalidade. Essa matriz é importante para que tanto o
A palavra 'consiste' foi escrita com dois s's, isto é, **conssite**.

2024-06-28 15:52 UTC, omatheu commented on docs/static/img/matriz-e-nao-e.png
No primeiro tópico do quadrante de 'É', acredito que seja equivocado dizer que os locadores vão gerenciar, conforme está escrito no primeiro tópico do quadrante, pois a administradora é contratada para cumprir esse papel.

2024-06-28 15:52 UTC, omatheu commented on docs/static/img/matriz-e-nao-e.png
Para ser mais correto, deve-se mudar o termo de imobiliária para administradora.

2024-06-28 18:33 UTC, Rodrigo-07 commented on docs/static/img/matriz-e-nao-e.png
Justo, vou arrumar isso

2024-06-28 18:35 UTC, Rodrigo-07 commented on docs/static/img/matriz-e-nao-e.png
Coloco só administradora ou administradora da imobiliária?

2024-06-28 18:36 UTC, Rodrigo-07 commented
> Fiquei com dúvida apenas no termo 'encargos'. Mas acredito que esta certo.

Eu coloquei "encargos" para generalizar custos adicionais, taxas, impostos e outras despesas obrigatórias.

2024-06-28 19:33 UTC, omatheu commented on docs/static/img/matriz-e-nao-e.png
Administradora mesmo.

2024-06-28 19:34 UTC, omatheu commented
Excelente trabalho @Rodrigo-07 !

2024-06-29 21:34 UTC, BretasArthur1 approved these changes
bem coerente com as reais funcionalidades

2024-07-01 08:57 UTC, omatheu approved these changes
Excelente!

2024-07-01 21:59 UTC, lucas-nunes-matheus approved these changes
Concordo com a matriz, acredito que está alinhado com o que a cliente pediu.

2024-07-01 22:11 UTC, renan-feitosa approved these changes

2024-07-01 22:17 UTC, merged