Documentation | Requisitos Funcionais e Não Funcionais
InteliJR/Imobiliaria pull request #15
Opened 2024-06-28 16:38 UTC by renan-feitosa

# :memo: Change Log
- Add 36 functional requirements
- Add 10 non-functional requirements

Closes #5

2024-06-28 18:25 UTC, Rodrigo-07 reviewed
Muito bom e completo 🚀. 

Não sei se é interresante mas a gnt poderia diminuir um pouco o numero de RF's, unindo eles, e detalhar mais os RNF's de cada RF.

2024-06-28 18:25 UTC, Rodrigo-07 commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-02: Funcionalidade de Login com Google
A gnt vai ter ambas as opções de logar com uma conta criada na plataforma e a conta do google?

2024-06-28 18:25 UTC, Rodrigo-07 commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-08: Assinatura de Contratos por Assinatura Digital
A gnt só não ia upar os contratos assinados? Foi até algo que a Tia falou que já pagava um serviço tipo do Docusign

2024-06-28 18:25 UTC, Rodrigo-07 commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-29: Upload de Boleto por PDF
Não vamos ter o serviço externo para gerar o meio de pagamento?

2024-06-28 19:33 UTC, omatheu commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-08: Assinatura de Contratos por Assinatura Digital
Exato! Concordo contigo @Rodrigo-07

2024-06-28 20:03 UTC, omatheu requested changes
Excelente trabalho @renan-feitosa!

Tem algumas coisas que gostaria que ajustasse.

2024-06-28 20:03 UTC, omatheu commented on docs/docs/Entendimento do problema/rf_rnf.md
> +O sistema deve ser capaz de enviar notificações por e-mail aos usuários quando novos contratos são assinados digitalmente.
Acredito que esse requisito deve ser modificado para: O sistema deve ser capaz de enviar notificações por e-mail aos usuários quando este for adicionado na plataforma, mencionando o contrato de locação em questão.

2024-06-28 20:34 UTC, renan-feitosa commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-06: Edição de Perfil
Alterei para que o usuário possa alterar somente sua senha e cabe a administradora editar quaisquer outras informações mediante contato externo. 

A parte de solicitação de revisão é interessante, mas acho que entra mais como nice to have também, vou deixar de fora dos requisitos por enquanto mas estou tomando nota das sugestões!

2024-06-28 20:35 UTC, renan-feitosa commented on docs/docs/Entendimento do problema/rf_rnf.md
> +### RF-08: Assinatura de Contratos por Assinatura Digital
Pelo que eu entendi da reunião, ela queria que tivesse uma integração com algum serviço de assinatura digital dentro da plataforma

2024-06-30 20:12 UTC, BretasArthur1 approved these changes

2024-07-01 01:56 UTC, Rodrigo-07 approved these changes

2024-07-01 08:58 UTC, omatheu approved these changes
Excelente @renan-feitosa ! 🎉👍🏾

2024-07-01 21:42 UTC, lucas-nunes-matheus approved these changes
Ótimo trabalho, @renan-feitosa! Auxiliou muito para a criação dos wireframes.

2024-07-01 22:15 UTC, merged