feat: Adiciona logica e rota de envio de email para quando o pagament…
InteliJR/Imobiliaria pull request #168
Opened 2024-11-01 23:52 UTC by BretasArthur1

…o esta prestes a vencer

2024-11-02 20:52 UTC, Rodrigo-07 requested changes
Boaaa, tá certinho a parte do email. Só uma questão, o admin, que vai enviar email por email?

2024-11-03 14:04 UTC, BretasArthur1 commented
na teoria é pra ser automático, porém coloquei a rota como adm para privar das outras roles e poder testar com o jwt, mas tb tive duvida nessa logica

2024-11-04 15:53 UTC, Rodrigo-07 commented
> na teoria é pra ser automático, porém coloquei a rota como adm para privar das outras roles e poder testar com o jwt, mas tb tive duvida nessa logica

Oq eu tinha entendido era que teria um crono job ou rota normal que pegario todos os locatarios que não tinham pago e ia enviar o email

2024-11-04 16:58 UTC, omatheu commented
Exatamente @Rodrigo-07 a ideia é ser automático... não cheguei a ver a implementação ainda, mas se não estiver assim, precisa de alteração no código.

2024-11-04 16:59 UTC, omatheu requested changes
1 - Alterar para o padrão esperado de Pull Requests

2024-11-04 23:09 UTC, closed without merging