FEATURE | api property
InteliJR/Imobiliaria pull request #192
Opened 2024-11-09 00:33 UTC by omatheu

# Changelog 📝 

- Adiciona CRUD para as entidades de contrato, imóveis etc.
- Adiciona o envio de notificação por email ao registrar um novo contrato;
- Relaciona documentos a uma determinada locação (contrato e vistoria, por exemplo).

2024-11-10 22:49 UTC, Rodrigo-07 requested changes
Otimoo, só levantei alguns pontos na parte do controler 🚀

2024-11-10 22:49 UTC, Rodrigo-07 commented on src/Property-service/Layer.Application/Controllers/ContratosController.cs
> +        public async Task<IActionResult> UpdateContrato(int id, [FromBody] Contratos novocontrato)
Se vc usa o objeto contratos como no body, a pessoa pode passar o contratoId mas como lá em baixo vc não passa isso é mais de boa

2024-11-10 22:49 UTC, Rodrigo-07 commented on src/Property-service/Layer.Application/Controllers/ContratosController.cs
> +            contrato.LocadorId = novocontrato.LocadorId;
Desse jeito eu preciso passar todas as informações do contrato mesmo que eu não vá alterar ela né?

2024-11-10 22:49 UTC, Rodrigo-07 commented on src/Property-service/Layer.Application/Models/NewChamado.cs
> +        public int IdChamado { get; set; }  // Identificador único do chamado
Acho que não precisa passar o IdChamado já que é feito pelo banco

2024-11-10 22:49 UTC, Rodrigo-07 commented on src/Property-service/Layer.Domain/Entites/Usuarios.cs
Precisa ter aqui nesse serviço essa etitie?

2024-11-10 22:49 UTC, Rodrigo-07 commented on src/Property-service/Layer.Domain/Entites/Usuarios.cs
Precisa ter aqui nesse serviço essa etitie?

2024-11-11 14:23 UTC, omatheu commented on src/Property-service/Layer.Application/Controllers/ChamadosController.cs
> +    [Route("api/[controller]")]
Foi intencional... mas posso melhorar, talvez deixar mais descritivo

2024-11-11 23:05 UTC, Rodrigo-07 commented on src/Property-service/Layer.Application/Controllers/ChamadosController.cs
> +    [Route("api/[controller]")]
Faz sentido é que só esse controller tem isso

2024-11-13 01:54 UTC, omatheu commented on src/Property-service/Layer.Application/Controllers/ContratosController.cs
> +            contrato.LocadorId = novocontrato.LocadorId;
Sim.

Não pensei em não colocar essas info. Da pra fazer sem precisar colocar todas as informações?

2024-11-13 12:42 UTC, Rodrigo-07 approved these changes
Boaaa Matt, muito bom. Já resolvi uns conflitos que tavam dando aqui também

2024-11-13 22:39 UTC, merged