feat: adiciona servico de logs ao servico de pagamentos
InteliJR/Imobiliaria pull request #210
Opened 2024-11-14 22:07 UTC by BretasArthur1

# ChangeLog:
- Adiciona servico de logs aos casos de uso de pagamentos
- Corrige estruturas de prod/dev
- ajuste de roles

closes: #154

2024-11-14 23:01 UTC, Rodrigo-07 requested changes
No geral tá certo mas faltou algumas coisas e vc não instalou o pacote do mongo na solução

2024-11-15 00:04 UTC, BretasArthur1 commented on src/Payment-service/Layer.Application/Controllers/PaymentController.cs
slk fui corrigir uns pacotes antes de commitar e tirei ele

2024-11-15 01:54 UTC, omatheu commented
@BretasArthur1 vc chegou testar pra ver se ta chegando log na onde deveria?

2024-11-15 01:56 UTC, omatheu approved these changes
Acredito que esteja tudo certo! Agora é testar com a instância do mongo db que esta em outra branch. Top!! @BretasArthur1

2024-11-15 01:56 UTC, merged