docs: Adiciona a nova matriz de riscos atualizada
InteliJR/Imobiliaria pull request #28
Opened 2024-07-03 20:16 UTC by lucas-nunes-matheus

Esta branch adiciona uma nova matriz de riscos atualizada.

2024-07-03 23:20 UTC, omatheu requested changes
@lucas-nunes-matheus trabalho excepcional!

Única coisa que vou solicitar alteração é a seguinte: não deletar a matriz de risco da sprint 1. Ao adicionar a nova matriz de risco, coloca o título da nova matriz como 'Matriz da sprint 2' e a anterior como 'Matriz de risco da sprint 1'. É uma boa pratica a atualização e monitoramento da matriz de risco de um projeto. Manter o histórico dos riscos mapeados demonstra maturidade da equipe.

2024-07-03 23:20 UTC, omatheu commented on docs/static/img/matriz_de_risco.png
Excelente trabalho @lucas-nunes-matheus, parabéns pela iniciativa de pegar para atulizar a matriz de risco dessa sprint!

2024-07-05 02:16 UTC, BretasArthur1 approved these changes
Muito bom Lucas! Matriz tras riscos reais do projeto a tona e riscos que percebemos durante o decorrer destas duas sprints

2024-07-11 17:32 UTC, omatheu approved these changes

2024-07-15 21:10 UTC, Rodrigo-07 approved these changes
Boaa

2024-07-17 01:59 UTC, renan-feitosa approved these changes

2024-07-18 22:24 UTC, merged