feat: conserta componente de menu
InteliJR/Imobiliaria pull request #282
Opened 2024-12-11 20:56 UTC by thiagomes07

# Changelogs 📝

- Conserta o menu;
- Move a Navbar e a centraliza pois antes havia desnecessáriamente duas NavBar.

closes #240

2024-12-12 13:06 UTC, omatheu commented
![image](https://github.com/user-attachments/assets/976f7a19-1278-4a8a-ac52-0c1242292cf9)


@thiagomes07

2024-12-12 13:09 UTC, omatheu requested changes
Temos problemas com a forma como os componentes estão sendo puxados.

2024-12-15 19:38 UTC, thiagomes07 commented
a develop agora foi devidamente integrada a esta branch, portanto, os conlitos já não existem. Além disso, o problema com a importação de algumas páginas também foram resolvidos.

2024-12-16 13:02 UTC, omatheu approved these changes
O menu ficou top!!! @thiagomes07

2024-12-16 13:02 UTC, merged