docs:Adiciona Arquitetura MACRO da solucao, nao envolvendo tecnologia…
InteliJR/Imobiliaria pull request #30
Opened 2024-07-05 02:14 UTC by BretasArthur1

…s especificas

2024-07-08 21:08 UTC, omatheu requested changes

2024-07-08 21:54 UTC, BretasArthur1 commented on docs/docs/Entendimento do problema/arquitetura.md
> +Esta arquitetura apresenta a  da nossa aplicação foi projetada para oferecer uma experiência robusta e segura para a gestão de imóveis. Com uma interface intuitiva e responsiva, o sistema permite que
Tranquilo Math, vou esperar geral dar os reviews e atualizo tudo

2024-07-10 23:53 UTC, lucas-nunes-matheus reviewed
Ótimo trabalho, @BretasArthur1 !
    Acredito que conseguiu desacoplar a tecnologia da arquitetura e destacar bem as funções da nossa API, assim como, o consumo de outras APIs.
    Além disso, acredito que poderia adicionar as funções de visualização de imóveis e de usuários (também disponíveis na aplicação).

2024-07-15 21:09 UTC, Rodrigo-07 reviewed
Gostei bastante e acho que os elementos estão certos mas tem algumas funções que tem na arquitetura de informação do Renan que não tem aqui. Seria bom a gnt alinhar isso

2024-07-18 22:27 UTC, merged