docs: Adicionando arquitetura da informaçao
InteliJR/Imobiliaria pull request #31
Opened 2024-07-09 00:52 UTC by renan-feitosa

# 📝 ChangeLog

- Adiciona arquitetura de informação do locatário
- Adiciona arquitetura de informação do locador
- Adiciona arquitetura de informação do administrador

Closes #10

2024-07-11 00:07 UTC, lucas-nunes-matheus requested changes
Ótimo trabalho, @renan-feitosa !
Facilitou muito na visualização de requisitos e de funcionalidades e auxiliou na construção dos wireframes.
É necessária uma mudança no acesso do administrador, caso concorde com a necessidade.

2024-07-11 00:07 UTC, lucas-nunes-matheus commented on docs/static/img/arquitetura_da_informacao_admnistrador.png
Ótimo trabalho na construção da Arquitetura da Informação! 
    As funcionalidades e os requisitos se tornaram mais claras com a estrutura de blocos para cada funcionalidade/página da aplicação.
    Acredito que poderia adicionar um bloco ao acesso do administrador: landing page > home > dashboard adm > "lista de boletos e contratos". A página de "lista de boletos e contratos" consulta os boletos e/ou contratos pendentes, a partir de filtros, e permite visualizar o imóvel relacionado àquele contrato ou boleto pendente.

2024-07-11 22:23 UTC, omatheu approved these changes
Excelente trabalho @renan-feitosa

2024-07-12 22:06 UTC, BretasArthur1 approved these changes

2024-07-15 20:29 UTC, Rodrigo-07 approved these changes
Boaa, ficou muito bo

2024-07-22 22:10 UTC, lucas-nunes-matheus approved these changes
De novo, ótimo trabalho, @renan-feitosa 

Só tem um detalhe, o título das 3 imagens está como "Arquitetura do Locatário".

Muito bom.

2024-07-22 22:46 UTC, merged