Documentacao Modelo Relacional e Fisico do Banco de Dados
InteliJR/Imobiliaria pull request #44
Opened 2024-07-24 03:13 UTC by BretasArthur1

2024-07-25 22:39 UTC, omatheu commented
![image](https://github.com/user-attachments/assets/5394536a-2aa7-4d85-9bfa-1c3dda98cf18)
Adicionar os tipos dos campos.

2024-07-26 15:25 UTC, lucas-nunes-matheus approved these changes
Conforme discutido e revisado na última revisão, ótimo trabalho! Parabéns!

2024-07-26 17:17 UTC, omatheu commented
Excelente trabalho @lucas-nunes-matheus ! 
Único ponto é o seguinte: existem alguns recursos específicos dentro dos principais provedores mapeados na sua análise importantes para o projeto, porque a ideia é utilizar os melhores recursos com o menor preço possível, agregando muito valor para o produto desenvolvido para a cliente. Como, por exemplo: dentro do provedor de serviços em Cloud (Google), existe o Firebase que é uma ferramenta completa, que entre outras coisas realiza o armazenamento de arquivos e da para usar de graça por um tempo. 
Pensando dessa forma, é possível criar um orçamento no mapeamento dos melhores recursos disponíveis, pelo melhor preço. Sem focar nos provedores, mas nas soluções que eles possuem. A análise deve fornecer para nós a melhor combinação de recursos e suas respectivas fontes, bem como o valor projetado para a sua utilização.

2024-07-27 11:21 UTC, omatheu requested changes
![image](https://github.com/user-attachments/assets/5394536a-2aa7-4d85-9bfa-1c3dda98cf18)
Adicionar os tipos dos campos.

2024-07-27 14:52 UTC, Rodrigo-07 approved these changes
Muito bom, acho que ficou bem claro as explicações.

2024-07-29 21:31 UTC, omatheu approved these changes
Boa!

2024-07-31 23:56 UTC, renan-feitosa requested changes

2024-07-31 23:56 UTC, renan-feitosa commented on docs/static/img/modelo_fisico-imob.png
Na relação entre imóveis e locadores, o certo não seria imóveis ter um campo de id_locador ou ser criada uma tabela intermediária para a relação se tornar n para n?

Do jeito que está agora, cada locador só pode ter um único imóvel por conta do campo id_imoveis, não?

2024-07-31 23:56 UTC, renan-feitosa commented on docs/static/img/modelo_fisico-imob.png
Acredito que a tabela de pagamentos não precisaria estar ligada diretamente com a tabela de contratos, pelo que eu consegui entender. Na hora de fazer consultas no banco de dados, já que os pagamentos necessariamente estão relacionados a algum aluguel, é só fazer esse caminho inverso.

2024-07-31 23:56 UTC, renan-feitosa commented on docs/static/img/modelo_fisico-imob.png
Não vale mais a pena guardar nº de passaporte, rg e cpf como string ao invés de int?

2024-07-31 23:56 UTC, renan-feitosa commented on docs/static/img/modelo_fisico-imob.png
A tabela de administradores vai ficar sem nenhum relacionamento com nenhuma outra mesmo? Imaginei que faria mais sentido deixar as credenciais dele na tabela usuário assim como os outros tipos de usuário

2024-08-01 23:03 UTC, omatheu commented on docs/static/img/modelo_fisico-imob.png
Excelente observação!

2024-08-01 23:06 UTC, Rodrigo-07 commented on docs/static/img/modelo_fisico-imob.png
No banco de dados que eu subi lá no supabase já tá como varchar

2024-08-01 23:30 UTC, Rodrigo-07 commented on docs/static/img/modelo_fisico-imob.png
![image](https://github.com/user-attachments/assets/23b18634-dd7c-4e1c-8185-991fdf45313f)

Otima observação. Alterei aqui já no banco de dados.
@BretasArthur1 aqui tá aquery atualizada de criação da tabela 

``` sql
-- public.imoveis definition

-- Drop table

-- DROP TABLE public.imoveis;

CREATE TABLE public.imoveis (
	id serial4 NOT NULL,
	tipo_imovel varchar NOT NULL,
	cep int4 NOT NULL,
	condominio int4 NOT NULL,
	valor_imovel numeric NULL,
	bairro varchar(100) NOT NULL,
	endereco_imovel varchar(100) NOT NULL,
	descricao varchar(100) NOT NULL,
	id_locador int4 NULL,
	CONSTRAINT imoveis_pkey PRIMARY KEY (id),
	CONSTRAINT imoveis_id_locador_fkey FOREIGN KEY (id_locador) REFERENCES public.locadores(id));`
```

``` sql
-- public.locadores definition

-- Drop table

-- DROP TABLE public.locadores;

CREATE TABLE public.locadores (
	id serial4 NOT NULL,
	nome_completo_locador varchar(200) NOT NULL,
	endereco varchar NOT NULL,
	passaporte int4 NULL,
	rg varchar(30) NULL,
	cpf varchar(30) NULL,
	nacionalidade varchar(50) NOT NULL,
	numero_telefone int4 NULL,
	email varchar(200) NOT NULL,
	id_usuarios int4 NULL,
	pessoa_juridica bool NULL,
	cnpj varchar NULL,
	CONSTRAINT locadores_pkey PRIMARY KEY (id),
	CONSTRAINT locadores_id_usuarios_fkey FOREIGN KEY (id_usuarios) REFERENCES public.usuarios(id)
);
```

2024-08-02 16:05 UTC, BretasArthur1 commented on docs/static/img/modelo_fisico-imob.png
o tipo int ocupa menos espaco na memoria, sendo mais eficiente para a alocacao do que o tipo string

2024-08-02 16:07 UTC, BretasArthur1 commented on docs/static/img/modelo_fisico-imob.png
precisa de estar para quando o pagamento for realizado, o contrato constar como pago e podermos exibir o status para o locatario/locador. E lembrando que os pagamentos sao feitos externamente da plataforma entao temos que ter eles conectados ao contrato

2024-08-02 16:09 UTC, BretasArthur1 commented on docs/static/img/modelo_fisico-imob.png
tem razao, apesar do tipo int ocupar menos espaco, as variaveis int geralmente sao utilizadas caso vamos fazer alguma operacao. nesse caso a sequenca de numeros e mlr ser varchar msm

2024-08-05 22:23 UTC, renan-feitosa approved these changes

2024-08-05 22:40 UTC, merged