Escolha de serviço de cloud
InteliJR/Imobiliaria pull request #46
Opened 2024-07-26 15:24 UTC by lucas-nunes-matheus

Essa branch contém o benchmark de serviços de cloud disponíveis no mercado para hospedagem da aplicação e para armazenamento de arquivos na nuvem.

2024-07-26 17:17 UTC, omatheu commented
Excelente trabalho @lucas-nunes-matheus !
Único ponto é o seguinte: existem alguns recursos específicos dentro dos principais provedores mapeados na sua análise importantes para o projeto, porque a ideia é utilizar os melhores recursos com o menor preço possível, agregando muito valor para o produto desenvolvido para a cliente. Como, por exemplo: dentro do provedor de serviços em Cloud (Google), existe o Firebase que é uma ferramenta completa, que entre outras coisas realiza o armazenamento de arquivos e da para usar de graça por um tempo.
Pensando dessa forma, é possível criar um orçamento no mapeamento dos melhores recursos disponíveis, pelo melhor preço. Sem focar nos provedores, mas nas soluções que eles possuem. A análise deve fornecer para nós a melhor combinação de recursos e suas respectivas fontes, bem como o valor projetado para a sua utilização.

2024-07-26 17:19 UTC, omatheu requested changes
O termo ERP foi mal-empregado para a representação da aplicação que estamos construindo. Pois, um ERP é uma solução que atua em todas as áreas de uma empresa, desde o comercial até o RH. Neste caso, nossa solução é especializada na gestão de imóveis.

2024-07-27 15:16 UTC, Rodrigo-07 requested changes
Parabéns ficou uma analise bem legal e detalhada. Só tem alguns pontos que acho que pode melhorar.

Se você usou aquelas calculadoras de orçamentos, geralmente eles geram um relatório com mais detalhes tipo esse https://cloud.google.com/products/calculator/estimate-preview/bd456610-120d-4819-a602-d4f82556feb6 . Se você tiver, acho que colocar ficaria top colocar porque acrescenta mais detalhes caso a gente precise.
Outra coisa é que seria interessante é explicar um pouco porque vocês o benchmarking com essas configurações "730 horas, Linux, 2 vCPUs, memória entre 3.5 e 4.3 GB e 50GB de armazenamento", porque isso ajuda a basear nossa decisão e explicar para a cliente esses serviços.
A ultima coisa é que seria bom também pelo menos elencar alguns serviços gratuitos, tipo Heroku, supabase, render, firebase, vercel. Por que apesar de que no futuro quando o site estiver 100% em produução o objetivo é colocar nesses serviços maiores, enquanto estamos desenvolvendo e para testar também é bom usar esses gratuitos.

2024-07-29 22:57 UTC, BretasArthur1 approved these changes

2024-07-30 12:37 UTC, omatheu requested changes
Excelente trabalho @lucas-nunes-matheus !

Existe um único ponto que senti falta na análise: o banco de dados SQL. Dentro da aplicação que estamos desenvolvendo, devido aos requisitos solicitados, teremos que utilizar um banco de dados para armazenamento de arquivos e outro para as informações do projeto. O segundo mencionado não foi estipulado o seu custo dentro da análise. Inicialmente sob a minha sugestão, estamos utilizando o Supabase como banco de dados, com isso é preciso estipular o valor de uma aplicação que utiliza esse recurso em produção e outros recursos possíveis de utilizar também.

2024-07-30 12:37 UTC, omatheu commented on docs/docs/Entendimento do problema/escolha_de_servico_de_cloud.md
> +        &emsp;&emsp;Nessa análise, com o objetivo de escalabilidade futura e de manutenção da aplicação em produção, avaliamos 5 (cinco) fornecedores principais de serviço na nuvem: Google Cloud Plat
O firebase faz parte do Google... pode ser considerada uma ferramenta desse provedor.

2024-07-30 12:37 UTC, omatheu commented on docs/docs/Entendimento do problema/escolha_de_servico_de_cloud.md
> +| Armazenamento de arquivos |   OCI  |   R$6   |
Não entendi o por que de colocar o armazenamento de arquivos da OCI, no texto sobre os serviços de armazenamento está claro que a melhor opção seria o Firebase.

2024-08-01 23:53 UTC, Rodrigo-07 approved these changes
Boaa monstro, melhorou muito!

2024-08-02 00:46 UTC, lucas-nunes-matheus commented on docs/docs/Entendimento do problema/escolha_de_servico_de_cloud.md
> +| Armazenamento de arquivos |   OCI  |   R$6   |
Realmente, @omatheu , cometi um equívoco na hora de construir a última tabela.

Irei corrigir, obrigado pela revisão atenta!

2024-08-02 00:50 UTC, lucas-nunes-matheus commented on docs/docs/Entendimento do problema/escolha_de_servico_de_cloud.md
> +        &emsp;&emsp;Nessa análise, com o objetivo de escalabilidade futura e de manutenção da aplicação em produção, avaliamos 5 (cinco) fornecedores principais de serviço na nuvem: Google Cloud Plat
Concordo que o Firebase é mantido pelo Google, contudo, os preços e as condições dos serviços oferecidos por ambos são consideravelmente diferentes - sendo assim, ficou evidente que o Firebase tem serviços mais destinados a aplicações de pequeno-médio porte, enquanto o GCP é um provedor de nuvem para aplicação mais robustas e exigentes.

Portanto, nessa análise, foi necessário separar ambos como provedores diferentes.

Obrigado pela revisão.

2024-08-02 01:00 UTC, lucas-nunes-matheus commented
> Excelente trabalho @lucas-nunes-matheus !
> 
> Existe um único ponto que senti falta na análise: o banco de dados SQL. Dentro da aplicação que estamos desenvolvendo, devido aos requisitos solicitados, teremos que utilizar um banco de dados para armazenamento de arquivos e outro para as informações do projeto. O segundo mencionado não foi estipulado o seu custo dentro da análise. Inicialmente sob a minha sugestão, estamos utilizando o Supabase como banco de dados, com isso é preciso estipular o valor de uma aplicação que utiliza esse recurso em produção e outros recursos possíveis de utilizar também.

Lucas: 
Perdão, acredito que houve um equívoco @omatheu .
Quando a referência ao Supabase foi feita no grupo e, pelo que eu entendi, até começou a ser usada para criar as tabelas no banco, acreditei iríamos usar o Supabase mesmo.
Além disso, da forma como tá no projects, a task inicialmente era somente de banco de dados para arquivos, então acabei não incluindo o banco de dados SQL.
Porém, sem problemas, irei adicionar um serviço para banco de dados!

2024-08-05 22:25 UTC, renan-feitosa approved these changes

2024-08-12 22:51 UTC, merged