Documentation/design software
InteliJR/Imobiliaria pull request #56
Opened 2024-08-04 13:39 UTC by omatheu

Adicionando a descrição da estrutura de design de software pensada para o desenvolvimento do sistema.

Segue alguns links que serão importantes para o melhor entendimento do conteúdo:

https://github.com/omatheu/layer-architecture

https://www.devmedia.com.br/arquitetura-em-camadas-com-csharp/12037

https://alexalvess.medium.com/criando-uma-api-em-net-core-baseado-na-arquitetura-ddd-2c6a409c686

2024-08-05 23:09 UTC, lucas-nunes-matheus approved these changes
Ótimo trabalho, @omatheu !

Explicação ficou bem clara.

2024-08-06 12:35 UTC, BretasArthur1 approved these changes
Boa @lucas-nunes-matheus e @omatheu apos a leitura do arquivo do medium ficou bem mais facil o entendimento

2024-08-08 14:27 UTC, Rodrigo-07 requested changes
Gostei acho uma boa decisão de arquitetura. Só duas coisas, não entendi muito bem pq tem uns commits relacionado as serviços de nuvem kkkkkkkkkkk e acho que seria legal colocar uma imagem de uma arquitetura em layer mais padrão (na vertical)

![image](https://github.com/user-attachments/assets/75c0052b-23ad-413e-8b8f-7f44b2b7b548)

Na horizontal dá mais foco na interação entre as camadas e na vertical é o jeito mais tradicional de mostrar a hierarquia e dependência das camadas de uma forma mais claro.

2024-08-09 01:50 UTC, omatheu commented
@Rodrigo-07 e @BretasArthur1 não sei exatamente o pq, mas pegou uns commits de cloud... coisa do repo que provável estava desatualizado quando eu peguei, peço que desconsiderem.

2024-08-09 02:17 UTC, omatheu commented
@Rodrigo-07 atualizei a doc com a imagem citada.

2024-08-09 11:48 UTC, Rodrigo-07 approved these changes
Boa, acho que tá bem completo

2024-08-09 12:01 UTC, renan-feitosa approved these changes

2024-08-09 12:22 UTC, merged