docs: Adiciona documentacao a respeito da estruturacao dos testes
InteliJR/Imobiliaria pull request #60
Opened 2024-08-06 23:49 UTC by BretasArthur1

2024-08-08 01:15 UTC, Rodrigo-07 requested changes
Muito bom, não achei nenhum problema grave apenas melhorias que podem deixar mais completo ainda.

2024-08-08 01:15 UTC, Rodrigo-07 commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
Existe um conceito que se chama Triple A (Arrange, Act, Assert) que é basicamente um padrão basico para garantir que o teste tenha tudo que precisa ter para ser um teste completo.  Vou mandar uns materiais mais detalhados mas basicamente acho que é interresante mencionar isso e geralmente o pessoalmente colocar comentários no código exibindo isso. Fica algo mais estruturado e legivel

```cs
      [Fact]
        public void Dividir_DoisDouble_RetornaDouble()
        {
            // Arrange  
            var num1 = 2.9;
            var num2 = 3.1;
            var valorEsperado = 0.94; //Rounded value  
            // Act  
            var div = Calculo.Dividir(num1, num2);
            //Assert  
            Assert.Equal(valorEsperado, div, 2);
        } 
 ```
        
  https://medium.com/@pablodarde/o-padr%C3%A3o-triple-a-arrange-act-assert-741e2a94cf88
  https://www.macoratti.net/19/09/cshp_unitest1.htm

2024-08-08 01:15 UTC, Rodrigo-07 commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
Algo que eu senti um pouco de falta foi explicar pq a utilização do xUnit e não MSTest ou NUnit. Não é contra a escolha, apenas acho legal mencionar tanto para o parceiro ter noção da escolha caso alguem mais técnico vá ver a doc e para a gnt criar bagagem nesse tópico

2024-08-08 01:15 UTC, Rodrigo-07 commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
No xUnit temos dois principais indicadores de testes o `Fact` e  o `Theory`. O fact é para testes mais simples que existe apenas um fato que precisar sair do teste e não tem entradas externas. O Theory é para testes que são baseados e dependentes de entradas de dados. ex:

```cs
[Theory]
[InlineData(3, 5, 8)]
[InlineData(2, 4, 6)]
[InlineData(6, 6, 12)]
public void AddNumbers(int a, int b, int expectedSum)
{
    int sum = a + b;
    Assert.Equal(expectedSum, sum);
}
```

Só acho interresante também colocar um exemplo

2024-08-08 01:15 UTC, Rodrigo-07 commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
Outra coisa legal que traz uma seriedade maior para o projeto é definir uma % cobertura de código minima, então preciso ter no minimo % de codigo coberto no meu projeto para ele passar. Isso é algo que não discutimos mas que pode ser interresante @omatheu tem até como automatizar isso no actions do github igual o docusauros

[cobertura de código](https://renatogroffe.medium.com/net-5-cobertura-de-testes-com-coverlet-7cbec2f052d9)

2024-08-09 12:08 UTC, omatheu commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
> +### Estrutura dos Testes de Integração
Em relação aos testes de integração, acredito que estão muito parecidos com os testes unitários dos endpoints... acredito que eles serão diferentes.

2024-08-09 12:09 UTC, omatheu approved these changes

2024-08-09 12:10 UTC, omatheu commented
@BretasArthur1 Bom trabalho! Acredito que em relação à estrutura dos testes do sistema, seu trabalho atingiu o objetivo.

2024-08-09 12:12 UTC, omatheu commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
DO KRLH essa sugestão @Rodrigo-07 !!

2024-08-09 12:30 UTC, renan-feitosa commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
Gigante. Quando corrigir isso aqui, eu adiciono a porcentagem como requisito não funcional de mantenabilidade também, foi uma parte que passou em branco

2024-08-09 12:45 UTC, renan-feitosa commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
> +### Estrutura dos Testes de Integração
Complementando o comentário do Matt, os testes unitários têm que garantir que cada "peça" do código se comporte conforme o esperado, sem interagir com outros módulos ou sistemas. Então, dentro da doc para o contexto de criação de usuário, dá pra colocar a verificação de funcionalidades autônomas tipo validação de email ou a criação de hash de senha.

Exemplo básico com Triple A:
```
[Fact]
public void HashPassword_ShouldReturnHashedPassword()
{
    // Arrange
    var password = "minhasenha1234";
    var hasher = new PasswordHasher();

    // Act
    var hashedPassword = hasher.HashPassword(password);

    // Assert
    Assert.NotEqual(password, hashedPassword);
}
```

Agora, seguindo o exemplo que você colocou na docs. Assim que seu teste envolve um banco de dados, ele não tá mais isolado, ou seja, depende de mais de um componente, módulo ou sistema. Então esse processo de receber dados do cliente, ajustá-los na regra de negócios (que não estão inseridos dentro do exemplo, mas isso não é necessário por enquanto anyway) e inserí-los no database é um teste de integração

2024-08-10 14:20 UTC, BretasArthur1 commented on docs/docs/Desenvolvimento técnico/estrutura _testes.md
Utilizei o xUnit por ser o com mais documntacao disponivel

2024-08-12 22:37 UTC, renan-feitosa approved these changes

2024-08-12 23:02 UTC, merged